trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'baxling/bulky'
  dockerfilePath: 'Dockerfile'
  buildContext: '.' # Byggkonteksten är rotmappen
  tag: 'latest'

steps:
# Steg 1: Checka ut koden
- checkout: self

# Steg 2: Återställ beroenden
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Steg 3: Bygg projektet
- task: DotNetCoreCLI@2
  displayName: 'Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration Release --no-restore'

# Steg 4: Kör tester
- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration Release --no-build --verbosity normal'

# Steg 5: Bygg och pusha Docker-imagen
- task: Docker@2
  displayName: 'Build and Push Docker Image'
  inputs:
    containerRegistry: 'dockerHubConnection'
    repository: '$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '$(dockerfilePath)'
    buildContext: '$(buildContext)'
    tags: |
      $(tag)
      $(Build.BuildId)
